name: sklearn-bio-workflows
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-affy
  - bioconductor-affyio
  - bioconductor-affyplm
  - bioconductor-apeglm
  - bioconductor-biobase
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-gcrma
  - bioconductor-limma
  - bioconductor-sva
  - bioconductor-variancepartition
  - joblib>=0.14
  - libopenblas
  - matplotlib
  - natsort
  - numpy
  - pandas
  - pillow
  - python
  - r-argparse
  - r-base
  - r-corpcor
  - r-devtools
  - r-essentials
  - r-fnn
  - r-fselector
  - r-jade
  - r-lme4
  - r-minqa
  - r-mnormt
  - r-nloptr
  - r-pamr
  - r-rcpparmadillo
  - r-rjava
  - r-statmod
  - rpy2=3.1
  - scikit-learn=0.21
  - seaborn
  - tabulate
