name: sklearn-bio-workflows
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-affy
  - bioconductor-affyio
  - bioconductor-affyplm
  - bioconductor-apeglm
  - bioconductor-biobase
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-gcrma
  - bioconductor-limma
  - bioconductor-sva
  - bioconductor-variancepartition
  - matplotlib
  - natsort
  - numpy=1.17
  - pandas=0.25
  - pillow
  - python=3.7
  - r-argparse
  - r-arules
  - r-base=3.6
  - r-bitops
  - r-catools
  - r-corpcor
  - r-devtools
  - r-e1071
  - r-essentials
  - r-fnn
  - r-fselector
  - r-jade
  - r-lme4
  - r-minqa
  - r-mnormt
  - r-nloptr
  - r-pamr
  - r-proc
  - r-rcpparmadillo
  - r-rcppeigen
  - r-rgl
  - r-rjava
  - r-rocr
  - r-statmod
  - rpy2=3.1
  - scikit-learn=0.21
  - seaborn
  - tabulate
